=== hansnone/10_01_2025_clase_xml_tarea/2_cv_pedro_de_cabo_arroyo.dtd
<!ELEMENT cv (nombre, direccion, telefono, fax?, email+, idiomas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT idiomas (idioma*)>
<!ELEMENT idioma (#PCDATA)>

=== hansnone/10_01_2025_clase_xml_tarea/2_cv_pedro_de_cabo_arroyo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "2_cv_pedro_de_cabo_arroyo.dtd">
<cv>
    <nombre>pedro de cabo</nombre>
    <direccion>calle optometrista 55, madrid, españa</direccion>
    <telefono>123456789</telefono>
    <email>nose2que@gmail,.com</email>
    <email>noseque@gmail,.com</email>
    <idiomas>
        <idioma>español</idioma>
        <idioma>ingles</idioma>
    </idiomas>
</cv>
